import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Dashbar from "@/shared/dashbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container flex gap-4 p-4">
          <div className="w-fit">
            <Dashbar />
          </div>
          <div className="flex-grow w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
